### PR TITLE
Fix AttributeError on Django 1.8

### PR DESCRIPTION
**Pull request by 1337**
Similar to [the fix by django-guardian](https://github.com/django-guardian/django-guardian/pull/336/files), Django 1.8 changes `.queryset` to `.get_queryset`. See issue for compatibility lists and test results.

### CODE REVIEW

**Comment by oivvio** [comment]
Thanks, does it still work with 1.7?

**Comment by 1337** [comment]
In theory, it does. The project itself doesn't seem to work with (a new) Django 1.7 (project) anyway:

```
$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "(...)/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "(...)/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "(...)/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "(...)/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "(...)/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "(...)/site-packages/emailuser/models.py", line 8, in <module>
    from django.contrib.auth.models import (
ImportError: cannot import name SiteProfileNotAvailable
```

**Comment by 1337** [comment]
Hey @oivvio , [one of your forks](https://github.com/RideCo/django-libtech-emailuser/commit/bd09926e2145d0aede09f484fce58d6c53180333) has a commit to support 1.7. Do you want that merged into your own repo?
